### PR TITLE
Add Defresh.js

### PR DESCRIPTION
**Pull request by stilic**
This little framework can accelerate page's load.
https://github.com/DerDer56/defresh

### CODE REVIEW

**Comment by trentwiles** [comment]
I'll add it as beta, I'm interested to see how it preforms with flag.

**Comment by trentwiles** [comment]
Ok, I gave it a shot and it works, but its a bit hard on the eyes. I'll consider sharing this video with the discord server to see what they think.

https://cdn.riverside.rocks/a/hide-talos-fig.mp4

**Comment by stilic** [comment]
try makes the halfmoon activate dark mode function loaded beforce the entire page is loaded.

**Comment by trentwiles** [comment]
I could try that, the halfmoon script does need to load for it to have dark mode. I'll ask the guy who makes halfmoon later today.

**Pull request merged**
